language: ruby
sudo: required

rvm:
  - 2.6.3

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker pull wrenchproject/wrench:1.6
  - mkdir data_server
  - docker-compose build --no-cache

notifications:
  email:
    recipients:
      - wrench@mailman.isi.edu
    on_success: change
    on_failure: always
  slack:
    secure: iblNKGB18NrNSHWsonO6jLpjqUxI7MhBYDHEAJxhN7sRCY4l9m4MhHGrVAndimeE2mWGqfl7nz9LjpGVrlc7y6y/8pNgaNwk1x1PLacOBjNdf+ZFx2b3p9+vXdcOyK3FO096er2V/MBWxUKrHYc3v1/9M/k8mwUYVRDeFfNMia+wgEWyS0p7mB84Q99KmUA6yvXlK0NPG1n/NwIcXaca8z7db1TeaYCpbR6N1f6I2eGMlJRYP4cYFbg141Qr9hpi0bkxTT+cMAuO+1WBQagZrMxh/O3BS6BvUVswBrxCP8zBG3H1lttkVSsIz3IdDzGoAXRNqY8X5sfrZlLEE2GoWlz3xAJtQoT2WGoubtL+sV4tDORhIPh+E5pbXMMI7HYTKAntJylRAJiifLQ8Cwz/5uo3+wyv+i/tM2iV72+6ykXO9vuuRHssvOETrwjXRP1sKfOoe2aeu2sFJNSq3daPGZZR0m7bIaXEVIy9+STfOt0AuamZggtgbU4EfsqjICkvna1IBNOjVIN8THBiyhMfQFoS5ezvQfqMcoL/NLZS5WlMuinNaxutWp+Yg1i9+QpFa5G1DJZ1SKtmMkaSQZn8ITPzxduOXOBvU4VJhbpIonbp6cBysI+iTyrlIWE6mnzWeEJ4ctDLSfNc1zUWLQAALKdlwshNgCOlaScTickSclo=
