language: ruby
sudo: required

rvm:
  - 2.6.3

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

script:
  - docker pull wrenchproject/wrench:unstable
  - mkdir data_server
  - docker-compose build --no-cache
