# Build settings
theme: minima
plugins:
  - jekyll-feed

# Dependencies
markdown:         kramdown
pygments:         true
highlighter:      rouge

# Permalinks
permalink:        pretty

#baseurl: '/'

# Setup
title:            'eduWRENCH - Pedagogic Modules'
tagline:          'Distributed Computing Courseware'
description:      'eduWRENCH Pedagogic Modules.'

author:
  name:           'WRENCH Team'
  url:            https://wrench-project.org

exclude:
  - node_modules
  - .idea
  - .jekyll-cache

#paginate:         5

# Custom vars
#version:          2.0.0

#github:
#  repo:           https://github.com/poole/lanyon

# include directory for pages
# include: ['_pages']

collections:
  pedagogic_modules:
    output: true
    permalink: /pedagogic_modules/:path/
  simulations:
    output: true
    permalink: /simulations/:path/
  assets:
    output: true
